project:
  type: website
  output-dir: docs

website:
  title: "Guillaume Blanc"
  navbar:
    background: "primary"
    foreground: white
    search: true
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: latent-book.qmd
        text: Book
      - href: cv.qmd
        text: CV
      - about.qmd

body-footer: | 
  Website designed with quarto by Guillaume Blanc. 2023 all rights reserved.

# Custom
page-layout: full
title-block-banner: "#f0f0f5"
title-block-banner-color: "#3d3d5c"


format:
  html:
    theme: 
      - simplex
      - custom.scss
    css: styles.css
    toc: true



