project:
  type: website
  output-dir: docs

website:
  title: "Guillaume Blanc"
  navbar:
    background: "primary"
    search: true
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - href: latent_book/_book/index.html
        text: Book
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



