project:
  type: website
  output-dir: docs

website:
  title: "Guillaume Blanc"
  navbar:
    background: "primary"
    search: true
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - href: latent-book.qmd
        text: Book
      - about.qmd

body-footer: | 
  Website designed with quarto by Guillaume Blanc. 2023 all rights reserved.

format:
  html:
    theme: 
      - simplex
      - custom.scss
    css: styles.css
    toc: true



